### ISSUE TITLE
Lz4File.read() shouldn't throw EOFError

### ISSUE THREAD

**Issue by dnuffer** [darkdragn/lz4tools#15]
The standard file objects in python return an empty string when EOF is reached. See https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects. "If the end of the file has been reached, f.read() will return an empty string ("")."
Throwing an exception makes it so that a Lz4File can't be substituted for a regular file.

**Comment by guoxiaoyong** [comment]
Agreed.
